//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeriTabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doktor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doktor()
        {
            this.Randevus = new HashSet<Randevu>();
        }
    
        public int Doktor_id { get; set; }
        public string Doktor_ad { get; set; }
        public string Doktor_TC { get; set; }
        public Nullable<int> Doktor_uzmanlik { get; set; }
        public Nullable<System.DateTime> Doktor_DOB { get; set; }
        public string Doktor_telefon { get; set; }
        public string Doktor_email { get; set; }
        public string Doktor_cinsyet { get; set; }
        public string Doktor_sifresi { get; set; }
        public Nullable<int> Kullanci_id { get; set; }
    
        public virtual Kullanci Kullanci { get; set; }
        public virtual Uzmanlik Uzmanlik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Randevu> Randevus { get; set; }
    }
}
