//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeriTabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanci
    {
        public int Kullanci_id { get; set; }
        public string Kullanci_adi { get; set; }
        public string Kullanci_email { get; set; }
        public string Kullanci_TC { get; set; }
        public string Kullanci_sifresi { get; set; }
        public string Kullanci_Yetki { get; set; }
    
        public virtual Doktor Doktor { get; set; }
        public virtual Kullanci Kullanci1 { get; set; }
        public virtual Kullanci Kullanci2 { get; set; }
    }
}
