//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeriTabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Randevu
    {
        public int Randevu_no { get; set; }
        public Nullable<System.DateTime> Randevu_date { get; set; }
        public Nullable<int> Doktor_id { get; set; }
        public Nullable<int> Hasta_id { get; set; }
        public Nullable<System.TimeSpan> Randevu_saati { get; set; }
    
        public virtual Doktor Doktor { get; set; }
        public virtual Hasta Hasta { get; set; }
    }
}
