//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeriTabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sekreter
    {
        public int Sekreter_id { get; set; }
        public string Sekreter_ad { get; set; }
        public string Sekreter_TC { get; set; }
        public string Sekreter_telefonb { get; set; }
        public string Sekreter_email { get; set; }
        public Nullable<System.DateTime> Sekreter_DOB { get; set; }
        public string Sekreter_sifresi { get; set; }
    }
}
